# Generated by Django 4.2.9 on 2024-09-23 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 6, 19, 42, 377439, tzinfo=datetime.timezone.utc)),
        ),
    ]
