# Generated by Django 4.2.16 on 2024-09-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('plot', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='%y/%b/%a/')),
            ],
        ),
    ]
